name: Build Java & Docker

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image Confluent
        id: docker_build_confluent
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: false
          tags: quickstart:latest

      - name: Build Docker Image Strimzi
        id: docker_build_strimzi
        uses: docker/build-push-action@v5
        with:
          file: strimzi.Dockerfile
          push: false
          tags: quickstart-strimzi:latest
